### ISSUE TITLE
The producer thread throw StackOverFlowException when CommitTransaction, if the Transaction Coordinator is down

### ISSUE THREAD

**Issue by cactus620** [confluentinc/confluent-kafka-dotnet#1321]
Description
===========
I have 3 Kafka brokers and I have the producer to send messages in a transaction.
I will take one broker down while producing messages to simulate a error. 
Then I found if I take down the specific broker 0 (guess it's the Transaction Coordinator for my transactional.id) the producer.CommitTransaction will always crash the thread by StackOverFlowException. 

Since my producer has a fixed transactional.id, it will only get back to work if I take broker 0 online again. This sounds a bit restrictive in a Kafka Cluster environment. Is there a way to have the Transaction Coordinator failover to another broker?

How to reproduce
================

1. Run following code, pass in at least two brokers.
2. Take down the 'Transaction Coordinator' before producer.CommitTransaction(), in my case, it's broker 0 running on port 9091.

```
	class Class1
	{
		private IProducer<string, string> producer;

		private string topic;
		private TimeSpan timeout = new TimeSpan(0, 0, 30);

		public Class1(string broker, string topic)
		{
			this.topic = topic;
			var config = GetProducerConfig(broker);

			CreateAvroProducer(config);
		}

		private Dictionary<string, string> GetProducerConfig(string broker)
		{
			var config = new Dictionary<string, string>();
			config.Add("bootstrap.servers", broker);
			config.Add("acks", "all");
			config.Add("message.timeout.ms", "10000");
			config.Add("retries", "2");
			config["transactional.id"] = "test-kafka-transaction";
			config["enable.idempotence"] = true.ToString();
			return config;
		}

		private void CreateAvroProducer(Dictionary<string, string> config)
		{
			producer = new ProducerBuilder<string, string>(config).Build();
			producer.InitTransactions(timeout);
			Console.WriteLine("Producer initialized.");
		}

		public void ProduceMessages()
		{
			try
			{
				producer.BeginTransaction();
				TestProduce();
				// Set break point here and take down the 'transaction coordinator'
				producer.CommitTransaction(timeout);
				Console.WriteLine("Producer transaction committed.");
			}
			catch (Exception ex)
			{
				Console.WriteLine("Unexpected exception: " + ex.Message);
			}
		}

		private void TestProduce()
		{
			for (int i = 1; i <= 10; i++)
			{
				var task = producer.ProduceAsync(topic, new Message<string, string>() { Key = $"{i}", Value = $"message {i}" });
				task.ContinueWith(tsk => {
					if (task.IsFaulted)
					{
						Console.WriteLine($"Error producing message: {task.Exception.Message}");
					}
					else
					{
						Console.WriteLine($"Message produced to offset : {task.Result.TopicPartitionOffset}");
					}
				});
			}
		}
	}
```

3. The program hung for a few seconds and crash. Got output on the console as below.

> Producer initialized.
> %6|1591860143.667|FAIL|rdkafka#producer-1| [thrd:TxnCoordinator]: TxnCoordinator: Disconnected (after 18209ms in state UP)
> %3|1591860143.667|ERROR|rdkafka#producer-1| [thrd:TxnCoordinator]: TxnCoordinator: Disconnected (after 18209ms in state UP)
> %6|1591860143.669|FAIL|rdkafka#producer-1| [thrd:XX.XX.XX.XX:9091/0]: XX.XX.XX.XX:9091/0: Disconnected (after 15851ms in state UP)
> %3|1591860143.669|ERROR|rdkafka#producer-1| [thrd:XX.XX.XX.XX:9091/0]: XX.XX.XX.XX:9091/0: Disconnected (after 15851ms in state UP)
> Message produced to offset : test2 [[0]] @21
> Message produced to offset : test2 [[0]] @23
> Message produced to offset : test2 [[0]] @22
> Message produced to offset : test2 [[0]] @24
> Message produced to offset : test2 [[0]] @26
> Message produced to offset : test2 [[0]] @28
> Message produced to offset : test2 [[0]] @25
> Message produced to offset : test2 [[0]] @27
> Message produced to offset : test2 [[0]] @29
> Message produced to offset : test2 [[0]] @30
> %3|1591860147.671|FAIL|rdkafka#producer-1| [thrd:TxnCoordinator]: TxnCoordinator: Connect to ipv4#XX.XX.XX.XX:9091 failed: No connection could be made because the target machine actively refused it... (after 4004ms in state CONNECT)
> %3|1591860147.671|ERROR|rdkafka#producer-1| [thrd:TxnCoordinator]: TxnCoordinator: Connect to ipv4#XX.XX.XX.XX:9091 failed: No connection could be made because the target machine actively refused it... (after 4004ms in state CONNECT)
> %3|1591860148.673|FAIL|rdkafka#producer-1| [thrd:XX.XX.XX.XX:9091/0]: XX.XX.XX.XX:9091/0: Connect to ipv4#XX.XX.XX.XX:9091 failed: No connection could be made because the target machine actively refused it... (after 4005ms in state CONNECT)
> %3|1591860148.673|ERROR|rdkafka#producer-1| [thrd:XX.XX.XX.XX:9091/0]: XX.XX.XX.XX:9091/0: Connect to ipv4#XX.XX.XX.XX:9091 failed: No connection could be made because the target machine actively refused it... (after 4005ms in state CONNECT)
> %3|1591860176.042|TXNERR|rdkafka#producer-1| [thrd:main]: Current transaction failed: Transactional operation timed out (_TIMED_OUT)
> %4|1591860207.686|REQTMOUT|rdkafka#producer-1| [thrd:TxnCoordinator]: TxnCoordinator: Timed out 0 in-flight, 0 retry-queued, 1 out-queue, 0 partially-sent requests
> 
> Process is terminated due to StackOverflowException.

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. 1.4.0, 1.4.3
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment]
i believe this is resolved by #1312

**Comment by cactus620** [comment]
@mhowlett , thanks for the quick response! I've had a try and now I can get an Exception after time out and fail elegantly. Will this be included in the 1.4.4 release? And is there a schedule for it?
Also on the other hand, I still can't get the producer to work until the 'key' broker is up and back online again. Shall I just keep trying to reconnect from the producer application? Or is there something more efficient to try? Appreciated for any suggestions.

**Comment by mhowlett** [comment]
"soon", waiting on librdkafka 1.4.4 which has some minor fixes (which have already been implemented). At one point it was going to be Friday. Would guess later this week.

**Comment by cactus620** [comment]
> "soon", waiting on librdkafka 1.4.4 which has some minor fixes (which have already been implemented). At one point it was going to be Friday. Would guess later this week.

@mhowlett I've noticed that 1.4.4 is available. After upgrading to 1.4.4, the issue is gone. Thanks!
Just another question regarding the high availability. If another broker is down, the producer can still send message. But if this 'Transaction Coordinator' is down, the producer is not able to send any message. Do you have any suggestion for this?

**Comment by milindl** [comment]
I understand that the transactional coordinator should fail over on its own. It's broker-side issue if it isn't failing over (the transaction coordinator is decided by the cluster). Since the original issue is now fixed closing this issue. There have been a lot of changes to the tx. producer code, too. Please reopen if it persists.
